# Change these first
owner: Cour-de-cassation # Your GitHub organization or username, where this repository lives
repo: judilibre-uptime # The name of this repository

sites:
  - name: www.courdecassation.fr recherche-judilibre
    url: https://www.courdecassation.fr/recherche-judilibre
    expectedStatusCodes: [200]
  - name: api.piste.gouv.fr healthcheck
    url: https://api.piste.gouv.fr/cassation/judilibre/v1.0/healthcheck
    expectedStatusCodes: [200]
    headers:
      - "KeyId: $API_KEY_PROD"
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: disponible
  - name: search.judilibre.io healthcheck
    url: https://search.judilibre.io/healthcheck
    expectedStatusCodes: [200, 301]
    __dangerous__body_down_if_text_missing: disponible
    maxResponseTime: 2000
  - name: search.prod-par2.judilibre.io healthcheck
    url: https://search.prod-par2.judilibre.io/healthcheck
    expectedStatusCodes: [200, 301]
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: disponible
  - name: search.prod-par1.judilibre.io healthcheck
    url: https://search.prod-par1.judilibre.io/healthcheck
    expectedStatusCodes: [200, 301]
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: disponible
  - name: search.dev.judilibre.io healthcheck
    url: https://search.dev.judilibre.io/healthcheck
    expectedStatusCodes: [200, 301]
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: disponible
  - name: sandbox-api.piste.gouv.fr healthcheck
    url: https://sandbox-api.piste.gouv.fr/cassation/judilibre/v1.0/healthcheck
    expectedStatusCodes: [200]
    headers:
      - "KeyId: $API_KEY_RECETTE"
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: disponible

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.judilibre.io
  favicon: https://raw.githubusercontent.com/Cour-de-cassation/judilibre-uptime/master/assets/cour-de-cassation.png
  faviconSvg: https://raw.githubusercontent.com/Cour-de-cassation/judilibre-uptime/master/assets/cour-de-cassation.svg
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Cour-de-cassation/judilibre-uptime/master/assets/Logo_judilibre_square.svg
  name: Statut de l'API
  introTitle: "**API Judilibre** - Cour de cassation"
  introMessage: Cette page présente le statut de l'API Judilibre, qui publie l'open data des décisions judiciaires, à l'aide de l'outil [Uptime.js.org](https://github.com/upptime/upptime).
  navbar:
    - title: Statut
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees: # Users to assign downtime issues (optional)
  - rhanka
